name: Devpass checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        run: sudo apt-get install python3

      - name: Download test file
        run: curl -0 https://devpass-api-bucket.s3.amazonaws.com/testes/devpass-community/challenge-1705946674186/test_main.py -o test_main.py

      - name: Run unit tests
        run: python3 test_main.py
